### PR TITLE
Fix some more spelling mistakes

### PR DESCRIPTION
**Pull request by Ghostkeeper**
These were found when we went through the texts for the translations.

### CODE REVIEW

**Comment by thopiekar** [comment]
Great! Thanks!

**Comment by thopiekar** [comment]
@Ghostkeeper: I uploaded a new plugin package under the same URL I shared before.

**Comment by Ghostkeeper** [comment]
I can't find any URL you shared with me before, thopiekar :confused:

**Comment by thopiekar** [comment]
There is a JIRA ticket for an update for the plugin.
I asked @Appesteijn for a review and thought you have been assigned to this.

**Comment by Ghostkeeper** [comment]
No, @diegopradogesto is assigned to that one. The current status of the update ticket is that the last test was done on February 16th and it still produced the same crashes on 0.5.2 as on 0.5.0. They are waiting for an update from you to fix those crashes.

The crashes in question are:

    TypeError: Cannot read property 'installationCheckDropdown' of null

and

    AttributeError: 'NoneType' object has no attribute 'getTransformed'

I don't know if that says anything to you. The tag is CURA-4549.

**Comment by diegopradogesto** [comment]
Yes @Ghostkeeper , @thopiekar and me are interchanging some emails about it. We are waiting for a new version.

**Comment by thopiekar** [comment]
Hey @diegopradogesto,

I was too busy until now.
Will write you a main in some minutes.

Have a nice weekend!

**Pull request merged**
