### PR TITLE
Fix macro so it can find "Ultimaker Cura"

### PR DESCRIPTION
**Pull request by LipuFei**
Because of the name change "Cura" -> "Ultimaker Cura", the old macro cannot find the new cura. This PR fixes the problem.

### CODE REVIEW

**Comment by thopiekar** [comment]
Great!

Could you please do the following:
 - [ ] rename macro/Plain_text_Macro.txt to macro/Export_to_Cura_2.x.plain.txt
 - [ ] Update the content of the plain file

Thanks!

**Comment by LipuFei** [comment]
@thopiekar The plain text macro has been updated.

**Comment by thopiekar** [comment]
Thanks.
Need to tag the releases here and will create a new .curaplugin file.

**Comment by thopiekar** [comment]
Cherry-picked and tagged all releases in git.

**Pull request closed without merging**
